M48
; DRILL file {KiCad 9.0.0} date 2025-04-18T01:08:40+1000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-18T01:08:40+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.250
%
G90
G05
T1
X101.65Y-55.29
X101.65Y-61.07
X101.65Y-72.43
X101.65Y-78.21
T2
X105.58Y-89.105
X105.58Y-100.535
M30
